# Generated by Django 2.0.7 on 2020-01-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
