# Generated by Django 2.0.7 on 2020-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200103_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='type',
            field=models.TextField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], null=True),
        ),
    ]
