# Generated by Django 2.0.7 on 2020-01-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_household_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='priority',
        ),
        migrations.AddField(
            model_name='member',
            name='missing_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='moved_out',
            field=models.BooleanField(default=False),
        ),
    ]
