# Generated by Django 2.0.7 on 2020-01-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0004_auto_20200105_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comps', models.ManyToManyField(related_name='companions', to='directory.Member')),
                ('ministerees', models.ManyToManyField(related_name='ministerees', to='directory.Member')),
            ],
        ),
    ]
